### ISSUE TITLE
Did everything the readme.md said, but it's just logging me into Bancho with the program running. Help?

### ISSUE THREAD

**Issue by justatesting1** [Igoorx/osuBancho#5]
I've done everything the readme.md said, edit the hosts file, compile with Visual Studio, import the SQL, etc, but it's still not working. Help? I've tried changing the IP from my localhost to my private IP, ???.???.?.??? in the Bancho.cs file, no results.

EDIT: Fixed, but I have another problem.

**Comment by justatesting1** [comment]
Fixed it myself, but I have another problem where it won't log me in, even on stable fallback.

**Comment by Igoorx** [comment]
Hello @justatesting1, the README.md file really is outdated because this repository is no longer being maintained, currently for you to connect to the Bancho the connection needs to be through **SSL**, I do not remember how this can be done in localhost unfortunately, maybe this is the problem that you have.

**Comment by justatesting1** [comment]
Alright, will Cloudflare SSL work? @Igoorx

**Comment by Igoorx** [comment]
@justatesting1 If you know how to set up, yes. You will also have to add the https prefix in [Bancho.cs#L126](https://github.com/Igoorx/osuBancho/blob/master/Bancho/Bancho.cs#L126)

**Comment by justatesting1** [comment]
@Igoorx Also, does 000webhost work with this because in the config I set it to databases.000webhost.com in the config.ini in /bin/Debug and it's throwing out "Can't connect to specified MySQL server.", I inputted everything right.

**Comment by justatesting1** [comment]
Just making sure.

**Comment by Igoorx** [comment]
@justatesting1 It should work with any MySQL-based database if the configuration is right.

**Comment by justatesting1** [comment]
@Igoorx I've tried 2 websites that have MySQL and phpmyadmin support, and it's still not working, double checked everything in my config.ini and Visual Studio 2017.
config.ini:
```
[Bancho]
Port = 80
Restricted = 0

[DatabaseConnection]
User = 1092146
Password = ???
Database = 1092146
Server = https://www.bamach.tk/pma/
Port = 3306

// Not recommended to edit
ConnectionTimeout = 10
CommandTimeout = 30
MaximumPoolSize = 250
MinimumPoolSize = 10

```
VS 2017:
```
using System;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.Text;
using System.Threading;
using System.Linq;
using MySql.Data.MySqlClient;
using osuBancho.Core.Players;
using osuBancho.Database;
using osuBancho.Database.Interfaces;
using osuBancho.Helpers;
using osuBancho.Core;
using osuBancho.Hosts.HTTP;
using osuBancho.Hosts.IRC;

namespace osuBancho
{
    static class Bancho
    {
        public static byte[] MOTD;
        public static byte Protocol = 19;
#if DEBUG
        public static bool IsDebug = false;
#else
        public static bool IsDebug = false;
#endif
        public static bool IsRestricted;
        public static CultureInfo CultureInfo;
        public static DateTime ServerStarted;

        public static IrcManager irc;

        private static Timer workerTimer;

        private static DatabaseManager _databaseManager;
        public static DatabaseManager DatabaseManager => _databaseManager; 

        static void Main()
        {
            ServerStarted = DateTime.Now;

            if (File.Exists("MOTD.txt"))
                MOTD = Encoding.Default.GetBytes($"<pre>\n{File.ReadAllText("MOTD.txt").InsertHrefInUrls()}\n</pre>");

            Console.Write("Initializing Bancho");
            if (IsDebug) Console.Write(" in debug mode");
            Console.WriteLine("..");

            Process.GetCurrentProcess().PriorityBoostEnabled = true;
            Process.GetCurrentProcess().PriorityClass = ProcessPriorityClass.RealTime;
            Thread.CurrentThread.Priority = ThreadPriority.Highest;

            Console.CursorVisible = false;
            Console.Title = (IsDebug?"[DEBUG] ":"") + "osu!Bancho";

            GeoUtil.Initialize();

            if (!File.Exists("config.ini"))
                File.WriteAllText("config.ini", IniFile.DefaultIni);

            IniFile ini = new IniFile("config.ini");
            Bancho.IsRestricted = ini.GetValue("Bancho", "Restricted", false);

            CultureInfo = CultureInfo.CreateSpecificCulture("en-GB");

            Console.WriteLine("Initializing Database..");

            var connectionString = new MySqlConnectionStringBuilder
            {
                ConnectionTimeout = ini.GetValue("DatabaseConnection", "ConnectionTimeout", 10u),
                Database = ini.GetValue("DatabaseConnection", "Database", "1092146"),
                DefaultCommandTimeout = ini.GetValue("DatabaseConnection", "CommandTimeout", 30u),
                Logging = false,
                MaximumPoolSize = ini.GetValue("DatabaseConnection", "MaximumPoolSize", 250u),
                MinimumPoolSize = ini.GetValue("DatabaseConnection", "MinimumPoolSize", 10u),
                Password = ini.GetValue("DatabaseConnection", "Password", "???"),
                Pooling = true,
                Port = ini.GetValue("DatabaseConnection", "Port", 3306u),
                Server = ini.GetValue("DatabaseConnection", "Server", "https://www.bamach.tk/pma"),
                UserID = ini.GetValue("DatabaseConnection", "User", "1092146"),
                AllowZeroDateTime = true,
                ConvertZeroDateTime = true,
            };

            _databaseManager = new DatabaseManager(connectionString.ToString());
            if (!_databaseManager.IsConnected())
            {
                Console.Error.WriteLine("Failed to connect to the specified MySQL server.");
                Console.ReadKey(true);
                Environment.Exit(1);
            }

            workerTimer = new Timer(
                (state) =>
                {
                    foreach (Player player in PlayerManager.Players
                        .Where(player => (Environment.TickCount - player.LastPacketTime) >= 80000))
                    {
                        PlayerManager.DisconnectPlayer(player, DisconnectReason.Timeout);
                    }
                    try
                    {
                        UpdateOnlineNow();
                    }
                    catch (Exception e)
                    {
                        Debug.WriteLine("Can't update onlines_now: " + e.Message);
                    }
                },
                null, 0, 15000);

#if DEBUG
            Debug.Listeners.Add(new ConsoleTraceListener());
#endif

            Console.WriteLine("Initializing IRC..");

            irc = new IrcManager();
            irc.Start();
            
            var port = ini.GetValue("Bancho", "Port", 80);
            Console.WriteLine($"Initializing HTTP in port {port.ToString()}..");

            HttpAsyncHost http = new HttpAsyncHost(IsDebug? 1 : 120);
            http.Run("https://+:"+port.ToString()+"/");

            Console.ReadLine();
        }

        public static void UpdateOnlineNow()
        {
            using (IQueryAdapter dbClient = DatabaseManager.GetQueryReactor())
            {
                dbClient.SetQuery("UPDATE osu_info SET value=@value WHERE name=@name");
                dbClient.AddParameter("name", "online_now");
                dbClient.AddParameter("value", PlayerManager.PlayersCount.ToString());
                dbClient.RunQuery();
            }
        }
    }
}

```

**Comment by Igoorx** [comment]
@justatesting1 Your config.ini is grossly wrong, you shouldn't use the URL of PHPMyAdmin, but the mysql's connection info. If you really wants to use a remote mysql, I recommend you to take a look at [this](https://radixcode.com/top-free-4-hosts-that-provide-remote-access-to-mysql-database).

**Comment by justatesting1** [comment]
@Igoorx Do you mean jdbc:mysql://localhost:3306/osu! as the mysql connection info or just https://localhost:3306? I'm a little confused.

**Comment by Igoorx** [comment]
No http(s). Lets say you use vertrigo on localhost, a valid config would be:
User = root
Password = vertrigo
Database = osu
Server = localhost
Port = 3306

**Comment by justatesting1** [comment]
@Igoorx
Using a different server fixed this, but now it's not letting me connect to the server, just failing to connect to Bancho when I set the hosts to the public IP of the website or the domain.
Hosts: 
```
45.61.159.32 osu.ppy.sh
45.61.159.32 c.ppy.sh
45.61.159.32 c1.ppy.sh
```

config.ini:
```
[Bancho]
Port = 80
Restricted = 0

[DatabaseConnection]
User = ???
Password = ???
Database = ???
Server = remotemysql.com
Port = 3306

// Not recommended to edit
ConnectionTimeout = 10
CommandTimeout = 30
MaximumPoolSize = 250
MinimumPoolSize = 10
```
PS: Also tried with:
Server = 45.61.159.32

**Comment by Igoorx** [comment]
The hosts should have the ip address where bancho is running (usually 127.0.0.1), not the mysql server ip address, and if you're using SSL on the bancho I think it's needed to it be in port 443

**Comment by justatesting1** [comment]
Edit: It might actually be timing out trying to connect as I just saw the program spit out timeout errors (pretty sure)
Edit 2: Might not be timing out actually.
![screenshot013](https://user-images.githubusercontent.com/47032613/53015952-4b61b780-341a-11e9-847b-5c0771e8dcb5.jpg)
@Igoorx I'm getting the error in the screenshot whenever I try connecting to the server with this config.ini:
[Bancho]
Port = 443
Restricted = 0

[DatabaseConnection]
User = ???
Password = ???
Database = ???
Server = remotemysql.com
Port = 3306

// Not recommended to edit
ConnectionTimeout = 10
CommandTimeout = 30
MaximumPoolSize = 250
MinimumPoolSize = 10

**Comment by Igoorx** [comment]
@justatesting1 You can look in the osu logs for the network file to see what problem it is giving, but by chance, did the osu's connect attempt appears on bancho console?

**Comment by justatesting1** [comment]
@Igoorx Where are the osu! logs, and the osu! connect did not appear in the Bancho console.

**Comment by Igoorx** [comment]
First you will need your osu! to be in the **cuttingedge** release stream to this file be created, then go to the root folder of osu! and you will see a folder called **Logs** and inside it will have the file **network.log**

**Comment by justatesting1** [comment]
@Igoorx I can't even get the server working on Stable without it connecting to normal Bancho, even with hosts file changed. It won't go away, so I can't change to cutting edge.

Config.ini:
[Bancho]
Port = 443
Restricted = 0

[DatabaseConnection]
User = ???
Password = ???
Database = ???
Server = 45.61.159.32
Port = 3306

// Not recommended to edit
ConnectionTimeout = 10
CommandTimeout = 30
MaximumPoolSize = 250
MinimumPoolSize = 10

**Comment by Igoorx** [comment]
Maybe the banho IP address has changed... I have seen that osu tries to connect to ce.ppy.sh now.
([and here is the osu.exe of cuttingedge](https://www77.zippyshare.com/v/CE66vLHr/file.html
))

**Comment by justatesting1** [comment]
@Igoorx 
This is my network.log:
2019-02-21T16:44:02: ----------------------------------------------------------
2019-02-21T16:44:02: Network Log for OldBo5
2019-02-21T16:44:02: osu! version unknown
2019-02-21T16:44:02: Running on Microsoft Windows NT 6.3.9600.0, 4 cores
2019-02-21T16:44:02: ----------------------------------------------------------
2019-02-21T16:44:02: Request to https://osu.ppy.sh/web/check-updates.php?action=check&stream=cuttingedge&time=636863462427193367 () failed with RequestTimeout (retrying 1/2).
2019-02-21T16:44:02: Request to https://osu.ppy.sh/web/check-updates.php?action=check&stream=cuttingedge&time=636863462427193367 () failed with RequestTimeout (retrying 2/2).
2019-02-21T16:44:02: Request to https://osu.ppy.sh/web/check-updates.php?action=check&stream=cuttingedge&time=636863462427193367 () failed with RequestTimeout (FAILED).
2019-02-21T16:44:04: Request to https://osu.ppy.sh/web/osu-error.php () failed with RequestTimeout (retrying 1/2).
2019-02-21T16:44:04: Request to https://osu.ppy.sh/web/osu-error.php () failed with RequestTimeout (retrying 2/2).
2019-02-21T16:44:04: Request to https://osu.ppy.sh/web/osu-error.php () failed with RequestTimeout (FAILED).
2019-02-21T16:44:08: Request to https://osu.ppy.sh/web/check-updates.php?action=check&stream=cuttingedge&time=636863462484529421 () failed with RequestTimeout (retrying 1/2).
2019-02-21T16:44:08: Request to https://osu.ppy.sh/web/check-updates.php?action=check&stream=cuttingedge&time=636863462484529421 () failed with RequestTimeout (retrying 2/2).
2019-02-21T16:44:08: Request to https://osu.ppy.sh/web/check-updates.php?action=check&stream=cuttingedge&time=636863462484529421 () failed with RequestTimeout (FAILED).
2019-02-21T16:44:13: Request to https://osu.ppy.sh/web/bancho_connect.php?v=b20190217cuttingedge&u=peppy&h=********************************&fx=dotnet30|dotnet35|dotnet4|dotnet4|dotnet4&ch=********************************************************************************************************************************************************************************************************************&retry=0 () failed with RequestTimeout (FAILED).
2019-02-21T16:44:13: Request to https://ce.ppy.sh () failed with RequestTimeout (retrying 1/2).
2019-02-21T16:44:13: Request to https://ce.ppy.sh () failed with RequestTimeout (retrying 2/2).
2019-02-21T16:44:13: Request to https://ce.ppy.sh () failed with RequestTimeout (FAILED).
2019-02-21T16:44:13: Request to https://osu.ppy.sh/web/bancho_connect.php?v=b20190217cuttingedge&u=peppy&h=********************************&fail=https://ce.ppy.sh () failed with RequestTimeout (retrying 1/2).
2019-02-21T16:44:13: Request to https://osu.ppy.sh/web/osu-checktweets.php () failed with RequestTimeout (retrying 1/2).
2019-02-21T16:44:13: Request to https://osu.ppy.sh/web/bancho_connect.php?v=b20190217cuttingedge&u=peppy&h=********************************&fail=https://ce.ppy.sh () failed with RequestTimeout (retrying 2/2).
2019-02-21T16:44:13: Request to https://osu.ppy.sh/web/osu-checktweets.php () failed with RequestTimeout (retrying 2/2).
2019-02-21T16:44:13: Request to https://osu.ppy.sh/web/bancho_connect.php?v=b20190217cuttingedge&u=peppy&h=********************************&fail=https://ce.ppy.sh () failed with RequestTimeout (FAILED).
2019-02-21T16:44:13: Request to https://osu.ppy.sh/web/osu-checktweets.php () failed with RequestTimeout (FAILED).

**Comment by justatesting1** [comment]
@Igoorx Hello? Read the above.

**Comment by Igoorx** [comment]
`2019-02-21T16:44:13: Request to https://ce.ppy.sh () failed with RequestTimeout (FAILED).
2019-02-21T16:44:13: Request to https://osu.ppy.sh/web/bancho_connect.php?v=b20190217cuttingedge&u=peppy&h=********************************&fail=https://ce.ppy.sh () failed with RequestTimeout (retrying 1/2).`
@justatesting1 This basically means that there's something wrong with your hosts, firewall or config.
Try to access [this link](https://ce.ppy.sh/) and if it doesn't connect to the bancho running to your PC, some of these things are wrong.

**Comment by justatesting1** [comment]
@Igoorx Looks like it's wrong, I've tried replacing 127.0.0.1 with 45.61.159.32 (remotemysql.com's IP) and changing the config.ini several times over, still connecting with:
                    ______                   __
  ____  _______  __/ / __ )____ _____  _____/ /_  ____
 / __ \/ ___/ / / / / __  / __ `/ __ \/ ___/ __ \/ __ \
/ /_/ (__  ) /_/ /_/ /_/ / /_/ / / / / /__/ / / / /_/ /
\____/____/\__,_(_)_____/\__,_/_/ /_/\___/_/ /_/\____/
osu!bancho (c) ppy Pty Ltd

                 .  o ..
                 o . o o.o
                      ...oo
                        __[]__
                     __|_o_o_o\__
                     \""""""""""/
                      \. ..  . /
                 ^^^^^^^^^^^^^^^^^^^^

web:    https://osu.ppy.sh
status: http://stat.ppy.sh / https://twitter.com/osustatus
boat:   https://twitter.com/banchoboat
hosts:
```
# Copyright (c) 1993-2009 Microsoft Corp.
#
# This is a sample HOSTS file used by Microsoft TCP/IP for Windows.
#
# This file contains the mappings of IP addresses to host names. Each
# entry should be kept on an individual line. The IP address should
# be placed in the first column followed by the corresponding host name.
# The IP address and the host name should be separated by at least one
#	space.
#
# Additionally, comments (such as these) may be inserted on individual
# lines or following the machine name denoted by a '#' symbol.
#
# For example:
#
#      102.54.94.97     rhino.acme.com          # source server
#       38.25.63.10     x.acme.com              # x client host
# localhost name resolution is handled within DNS itself.
#	127.0.0.1       localhost
#	::1             localhost
# rss test 7454f737-2377-481c-951b-15231b5273b4

45.61.159.32 osu.ppy.sh
45.61.159.32 c.ppy.sh
45.61.159.32 c1.ppy.sh
45.61.159.32 ce.ppy.sh
```

config.ini:
```
[Bancho]
Port = 443
Restricted = 0

[DatabaseConnection]
User = ???
Password = ???
Database = ???
Server = remotemysql.com
Port = 3306

// Not recommended to edit
ConnectionTimeout = 10
CommandTimeout = 30
MaximumPoolSize = 250
MinimumPoolSize = 10
```

**Comment by justatesting1** [comment]
@Igoorx Read the above.

**Comment by justatesting1** [comment]
Just checking to see if your notifications got flooded.

**Comment by justatesting1** [comment]
@Igoorx Hello?
yes i'm acting impatient but i wanna get this done because its always in my mind

**Comment by Igoorx** [comment]
@justatesting1 Hello, are you using Bancho in debug mode? Because advanced logs only appear in this mode. And I've noticed that `ce.ppy.sh` is just for the cuttingedge, so be careful! Besides that, are you using the SSL certificate?

**Comment by justatesting1** [comment]
@Igoorx Yes, I am using the SSL certificate, but it's red in Chrome in the corner, don't know if that's the cause but the exe spat out tons of errors.
```
osu!Bancho.exe Warning: 0 : Could not kill query,  aborting connection. Exception was The handshake failed due to an unexpected packet format.
MySql.Data.MySqlClient.MySqlException (0x80004005): Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. ---> System.TimeoutException: Timeout in IO operation
   at MySql.Data.MySqlClient.TimedStream.StopTimer()
   at MySql.Data.MySqlClient.TimedStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.BufferedStream.Read(Byte[] array, Int32 offset, Int32 count)
   at MySql.Data.MySqlClient.MySqlStream.ReadFully(Stream stream, Byte[] buffer, Int32 offset, Int32 count)
   at MySql.Data.MySqlClient.MySqlStream.LoadPacket()
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   at MySql.Data.MySqlClient.MySqlConnection.HandleTimeoutOrThreadAbort(Exception ex)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at osuBancho.Database.Adapter.QueryAdapter.RunQuery() in C:\Users\OldBo5\Desktop\osuBancho-master\Bancho\Database\Adapter\QueryAdapter.cs:line 175
MySql.Data.MySqlClient.MySqlException (0x80004005): Fatal error encountered during command execution. ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Fatal error encountered attempting to read the resultset. ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Reading from the stream has failed. ---> System.IO.IOException: The read operation failed, see inner exception. ---> System.TimeoutException: Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. ---> System.IO.IOException: Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at MySql.Data.Common.MyNetworkStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   --- End of inner exception stack trace ---
   at MySql.Data.Common.MyNetworkStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.Net.FixedSizeReader.ReadPacket(Byte[] buffer, Int32 offset, Int32 count)
   at System.Net.Security._SslStream.StartFrameHeader(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security._SslStream.StartReading(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security._SslStream.ProcessRead(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   --- End of inner exception stack trace ---
   at System.Net.Security._SslStream.ProcessRead(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at MySql.Data.MySqlClient.TimedStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.BufferedStream.Read(Byte[] array, Int32 offset, Int32 count)
   at MySql.Data.MySqlClient.MySqlStream.ReadFully(Stream stream, Byte[] buffer, Int32 offset, Int32 count)
   at MySql.Data.MySqlClient.MySqlStream.LoadPacket()
   at MySql.Data.MySqlClient.MySqlStream.LoadPacket()
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at osuBancho.Database.Adapter.QueryAdapter.RunQuery() in C:\Users\OldBo5\Desktop\osuBancho-master\Bancho\Database\Adapter\QueryAdapter.cs:line 175
MySql.Data.MySqlClient.MySqlException (0x80004005): Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. ---> System.TimeoutException: Timeout in IO operation
   at MySql.Data.MySqlClient.TimedStream.StopTimer()
   at MySql.Data.MySqlClient.TimedStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.BufferedStream.Read(Byte[] array, Int32 offset, Int32 count)
   at MySql.Data.MySqlClient.MySqlStream.ReadFully(Stream stream, Byte[] buffer, Int32 offset, Int32 count)
   at MySql.Data.MySqlClient.MySqlStream.LoadPacket()
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   at MySql.Data.MySqlClient.MySqlConnection.HandleTimeoutOrThreadAbort(Exception ex)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at osuBancho.Database.Adapter.QueryAdapter.RunQuery() in C:\Users\OldBo5\Desktop\osuBancho-master\Bancho\Database\Adapter\QueryAdapter.cs:line 175
MySql.Data.MySqlClient.MySqlException (0x80004005): Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. ---> System.TimeoutException: Timeout in IO operation
   at MySql.Data.MySqlClient.TimedStream.StopTimer()
   at MySql.Data.MySqlClient.TimedStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.BufferedStream.Read(Byte[] array, Int32 offset, Int32 count)
   at MySql.Data.MySqlClient.MySqlStream.ReadFully(Stream stream, Byte[] buffer, Int32 offset, Int32 count)
   at MySql.Data.MySqlClient.MySqlStream.LoadPacket()
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   at MySql.Data.MySqlClient.MySqlConnection.HandleTimeoutOrThreadAbort(Exception ex)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at osuBancho.Database.Adapter.QueryAdapter.RunQuery() in C:\Users\OldBo5\Desktop\osuBancho-master\Bancho\Database\Adapter\QueryAdapter.cs:line 175
osu!Bancho.exe Error: 0 : Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.
osu!Bancho.exe Warning: 0 : Could not kill query,  aborting connection. Exception was Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.
MySql.Data.MySqlClient.MySqlException (0x80004005): Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. ---> System.TimeoutException: Timeout in IO operation
   at MySql.Data.MySqlClient.TimedStream.StopTimer()
   at MySql.Data.MySqlClient.TimedStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.BufferedStream.Read(Byte[] array, Int32 offset, Int32 count)
   at MySql.Data.MySqlClient.MySqlStream.ReadFully(Stream stream, Byte[] buffer, Int32 offset, Int32 count)
   at MySql.Data.MySqlClient.MySqlStream.LoadPacket()
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   at MySql.Data.MySqlClient.MySqlConnection.HandleTimeoutOrThreadAbort(Exception ex)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at osuBancho.Database.Adapter.QueryAdapter.RunQuery() in C:\Users\OldBo5\Desktop\osuBancho-master\Bancho\Database\Adapter\QueryAdapter.cs:line 175
```

**Comment by justatesting1** [comment]
@Igoorx

**Comment by justatesting1** [comment]
@Igoorx

**Comment by hazel0177** [comment]
Never contributed, but I suggest using a server switcher and/or fallback

fallback requires 0 ssl.

**Comment by lokillo-0** [comment]
I understand that this program was made to run on a local PC so I do not see it necessary to use a server switcher, you just have to modify the hosts file

**Comment by hazel0177** [comment]
does anyone haave https://github.com/Igoorx/osuPatcher
lowkey

**Comment by Igoorx** [comment]
@justatesting1 sorry, I ended up forgetting about you lol, but I think you are doing something very wrong.
@0176 I brought back the repository, not exactly how it was but just the source code that I found in my HD. I shouldn't have even killed this repository in the first place but it's a shame I did it. But, be sure to know that that project is from 2016, it may not work with 2019 osu.

**Comment by hazel0177** [comment]
@Igoorx can I modify it for 2013 and previous?

If you have discord, my tag is ilyt#1936 and I can explain why

**Comment by justatesting1** [comment]
@Igoorx oh hey just logged onto github for the first time in like 6 months i dont even have it on my HDD anymore its on my windows 10 hdd which is super slow so im gonna have to dig it out of there and put it on my windows 8.1 hdd
